server:
  port: 8090

spring:
  application:
    name: gateway-service
  #main:
  #  web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Gateway, gateway-service
            - name: RateLimiter

        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AddRequestHeader=X-Gateway, gateway-service

        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/api/admin/**
          filters:
            - AddRequestHeader=X-Gateway, gateway-service

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AddRequestHeader=X-Gateway, gateway-service
        
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**
          filters:
            - AddRequestHeader=X-Gateway, gateway-service

        # Swagger doc route for aggregation
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user, /v3/api-docs

        - id: product-service-swagger
          uri: lb://product-service
          predicates:
            - Path=/v3/api-docs/product
          filters:
            - RewritePath=/v3/api-docs/product, /v3/api-docs
        
        - id: media-service-swagger
          uri: lb://media-service
          predicates:
            - Path=/v3/api-docs/media
          filters:
            - RewritePath=/v3/api-docs/media, /v3/api-docs

# Swagger config
springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true
    urls:
      - name: user-service
        url: /v3/api-docs/user
      - name: product-service
        url: /v3/api-docs/product
      - name: media-service
        url: /v3/api-docs/media

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: N5Dztk+QsQEOFEhZ9WZ7ZzRp7uuOoT/knKWvYVZLNS7vt8BjnfHxLjzjGdBfEBu3
  expiration: 3600000

# Internal token for service-to-service communication
internal:
    token-header: X-INTERNAL-TOKEN
    token: NyKKbcadVWq1Mim/r7vwzPjy0SikZgFOiYJRO8GvE1A=
